# Generated by Django 4.1.7 on 2023-06-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "placeid",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="場所ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="名前"),
                ),
                ("address", models.CharField(max_length=50, verbose_name="住所")),
                ("descpiption", models.TextField(max_length=500, verbose_name="説明")),
                ("accsess", models.CharField(max_length=200, verbose_name="アクセス")),
                ("notes", models.TextField(max_length=400, verbose_name="備考")),
                (
                    "praceimage",
                    models.ImageField(upload_to="place_images/", verbose_name="画像"),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="緯度"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="経度"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="prace_images/", verbose_name="画像"),
                ),
                (
                    "animeid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anime",
                        to="anime.anime",
                    ),
                ),
            ],
            options={"verbose_name": "場所", "verbose_name_plural": "場所",},
        ),
    ]
