# Generated by Django 4.1.7 on 2023-06-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_alter_place_lat_alter_place_lng"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place", old_name="praceimage", new_name="placeimage",
        ),
    ]
