# Generated by Django 4.1.7 on 2023-06-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_alter_anime_title"),
        ("map", "0006_rename_praceimage_place_placeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="animetitle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animetitle",
                to="anime.anime",
                to_field="title",
            ),
            preserve_default=False,
        ),
    ]
