# Generated by Django 4.1.7 on 2023-06-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anime", "0001_initial"),
        ("map", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "postid",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="投稿ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=500)),
                (
                    "postimage",
                    models.ImageField(upload_to="post_images/", verbose_name="画像"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animeid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animeid",
                        to="anime.anime",
                    ),
                ),
                (
                    "praceid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="map.place",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.user",
                        to_field="userid",
                    ),
                ),
            ],
        ),
    ]
