# Generated by Django 4.1.7 on 2023-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_images/", verbose_name="画像"
            ),
        ),
    ]
