# Generated by Django 4.1.7 on 2023-06-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_postimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="praceid", new_name="placeid",
        ),
    ]
