# Generated by Django 4.1.7 on 2023-06-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_rename_anineid_anime_animeid"),
        ("post", "0003_rename_praceid_post_placeid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="animeid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anime_id",
                to="anime.anime",
            ),
        ),
    ]
