# Generated by Django 4.2.2 on 2023-07-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_place_animetitle"),
        ("post", "0004_alter_post_animeid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="placename",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postname",
                to="map.place",
                to_field="name",
            ),
            preserve_default=False,
        ),
    ]
