# Generated by Django 4.2.2 on 2023-07-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_placename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postid",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="投稿ID"
            ),
        ),
    ]
