# Generated by Django 4.2.2 on 2023-07-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_place_animetitle"),
        ("post", "0006_alter_post_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="placename",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postname",
                to="map.place",
                to_field="name",
            ),
        ),
    ]
