# Generated by Django 4.1.7 on 2023-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.CharField(max_length=15, unique=True, verbose_name="userid"),
        ),
    ]
