# Generated by Django 4.2.2 on 2023-07-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="token",),
    ]
