# Generated by Django 4.1.7 on 2023-06-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "amineid",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "animeimage",
                    models.ImageField(upload_to="anime_images/", verbose_name="アニメ写真"),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("related", models.CharField(max_length=200)),
            ],
        ),
    ]
