# Generated by Django 4.1.7 on 2023-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="anime", name="related",),
        migrations.AlterField(
            model_name="anime",
            name="description",
            field=models.CharField(max_length=500, verbose_name="あらすじ"),
        ),
    ]
