# Generated by Django 4.1.7 on 2023-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_remove_anime_related_alter_anime_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
