# Generated by Django 4.1.7 on 2023-06-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_alter_anime_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anime", old_name="amineid", new_name="anineid",
        ),
    ]
